repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
      - id: check-case-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.2
    hooks:
      - id: cspell
