name: Deploy image to ghcr.io

on:
  push:
    tags:
      - v*
    paths:
      - cmd/**
      - internal/**
      - pkg/**
      - Dockerfile
      - .dockerignore
      - .golangci.yml
      - go.mod
      - go.sum

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions: # Permissions for GITHUB_TOKEN
      contents: read
      packages: write
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          username: bl4ko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: bl4ko
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Build and push final image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7
          tags: |
            bl4ko/netbox-ssot:latest
            bl4ko/netbox-ssot:${{ github.ref_name }}
            ghcr.io/bl4ko/netbox-ssot:latest
            ghcr.io/bl4ko/netbox-ssot:${{ github.ref_name }}
          push: true
