name: Deploy image to ghcr.io

on:
  push:
    tags:
      - v*
    paths:
      - cmd/**
      - internal/**
      - pkg/**
      - Dockerfile
      - .dockerignore
      - .golangci.yml
      - go.mod
      - go.sum

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions: # Permissions for GITHUB_TOKEN
      contents: read
      packages: write
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: bl4ko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: bl4ko
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3

      - name: Build and push final image
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5.2.0
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7
          tags: |
            bl4ko/netbox-ssot:latest
            bl4ko/netbox-ssot:${{ github.ref_name }}
            ghcr.io/bl4ko/netbox-ssot:latest
            ghcr.io/bl4ko/netbox-ssot:${{ github.ref_name }}
          push: true
