name: Deploy image to ghcr.io

on:
  push:
    tags:
      - v*
    paths:
      - cmd/**
      - internal/**
      - pkg/**
      - Dockerfile
      - .dockerignore
      - .golangci.yml
      - go.mod
      - go.sum

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions: # Permissions for GITHUB_TOKEN
      contents: read
      packages: write
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          username: bl4ko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: bl4ko
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3

      - name: Build and push final image
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd # v6.4.0
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7
          tags: |
            bl4ko/netbox-ssot:latest
            bl4ko/netbox-ssot:${{ github.ref_name }}
            ghcr.io/bl4ko/netbox-ssot:latest
            ghcr.io/bl4ko/netbox-ssot:${{ github.ref_name }}
          push: true
