name: Continious integration

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests and upload results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21", "1.22"]

    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      # This is currently workaround for checking if gofiles have changed,
      # Because paths filter doesn't work with required checks
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v44
        with:
          files: |
            cmd/**
            internal/**
            .golangci.yml
            go.mod
            go.sum

      - name: Setup Go
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
        with:
          version: latest
          args: --timeout=5m

      - name: Install dependencies
        if: steps.changed-files.outputs.any_modified == 'true'
        run: go mod download

      - name: Test with Go
        if: steps.changed-files.outputs.any_modified == 'true'
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cover.txt
          slug: bl4ko/netbox-ssot

  vulnerabilities:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v44
        with:
          files: |
            cmd/**
            internal/**
            .golangci.yml
            go.mod
            go.sum
            .dockerignore
            Dockerfile

      # https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#scan-ci-pipeline
      - name: Build an image from Dockerfile
        if: steps.changed-files.outputs.any_modified == 'true'
        run: |
          docker build -t netbox-ssot:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: netbox-ssot:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
