name: Check spelling with spellcheck
on:
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: streetsidesoftware/cspell-action@807d7d92b7057593a2de102168506f298405339d # v6
