name: Check spelling with spellcheck
on:
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: streetsidesoftware/cspell-action@245201e3f58019204d99920deeb78aade6724230 # v6
